global:
  scrape_interval: 10s
  evaluation_interval: 10s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#            - alertmanager:9093

scrape_configs:
  - job_name: "locahlost-node-exporter"
    metrics_path: /prometheus/node-exporter/metrics
    static_configs:
      - targets:
        - hubble.locahlost.net
        - endeavour.locahlost.net
        - kourou.locahlost.net
        - melisse.locahlost.net

  - job_name: "locahlost-zfs-exporter"
    metrics_path: /prometheus/zfs/metrics
    static_configs:
      - targets:
        - endeavour.locahlost.net

  - job_name: "locahlost-postgres-exporter"
    metrics_path: /prometheus/postgres/metrics
    static_configs:
      - targets:
        - endeavour.locahlost.net
